spring:
  application:
    name: Edu-AI-backend-local

  # --- H2 In-memory Database for Local ---
  h2:
    console:
      enabled: true
      path: /h2-console

  # --- Datasource Configuration ---
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:aithon-db;DB_CLOSE_DELAY=-1
    username: sa
    password:

  # --- JPA & Hibernate Configuration ---
  jpa:
    hibernate:
      ddl-auto: update # Use update to create tables automatically in H2
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # --- Liquibase Configuration (Disabled for local) ---
  liquibase:
    enabled: false

  # --- OAuth2 Client (Google) ---
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

# --- JWT (JSON Web Token) ---
jwt:
  secret: 8616e8c057898e393f7e5d1abe4137849baee8e092cc91cd1a21c3be7fde0e95
  access-token-validity-in-seconds: 3600 # 1 hour
  refresh-token-validity-in-seconds: 86400 # 1 day

# --- CORS settings ---
cors:
  allowed-origins: http://localhost:5173
