spring:
  application:
    name: Edu-AI-backend

  # --- Datasource Configuration ---
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/edu_ai?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # --- JPA & Hibernate Configuration ---
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

  # --- Liquibase Configuration ---
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
    enabled: true
    contexts: local
